
server:
  port: ${port:10010}
#  servlet:
#     context-path: /rbac/
spring.application.name: unity-server-rbac

#logbook:
#  write:
#    level: info
#  format:
#    style: http

spring.profiles.include:
  - db
  - freemarker
  - mybatis
  - amqp
  - common
  - redis


spring:
  security:
    model: permit
    permit:
      - /sys/login
      - /sys/logout
      - /identity/saveUserIdentiryList/*
      - /api/user/pushUcsUserToSecurity
      - /resource/saveRoleResource
      - /ipldarbmain/exportExcel
      - /iplEsbMain/export/excel
      - /iplManageMain/downloadIplSatbMainDataPkgToExcel/*
      - /iplOdMain/export/excel
      - /iplSuperVisionMain/download
      - /sysCfg/list