spring:
#  session:
#    store-type: redis
  redis:
    topic: __keyevent@0__:expired
    namespace: sessionRBAC
    flush-mode: on-save
    timeout: 2000
    return: true
    borrow: true
    jedis:
      pool:
        max-idle: 50
        min-idle: 20
        max-active: 200
        max-wait: 3000D

---
spring:
  profiles: devel
  redis:
   port: 6379
   host: 172.19.1.97
   password: Jingkai@jingcaiwang.cn

---

spring:
  profiles: test
  redis:
      port: 6379
      host: 172.19.1.97
      password: Jingkai@jingcaiwang.cn
---

spring:
  profiles: uat
  redis:
      port: 6379
      host: 172.19.1.62
      password: Jingkai@jingcaiwang.cn
---
spring:
  profiles: prod
  redis:
     port: 6379
     host: 192.168.2.59
     password: Jingkai@jingcaiwang.cn
