
server:
  port: ${port:10060}
#  servlet:
#     context-path: /ipa/
spring.application.name: unity-business-innovation

#logbook:
#  write:
#    level: info
#  format:
#    style: http

spring.profiles.include:
  - db
  - freemarker
  - mybatis
  - amqp
  - common
  - redis
spring:
  security:
    model: permit
    permit:
      - /ipldarbmain/saveOrUpdate
      - /iplEsbMain/saveOrUpdate
      - /iplOdMain/saveOrUpdate
      - /iplpdmain/saveOrUpdate
      - /iplsatbmain/saveOrUpdate
      - /iplSuggestion/saveOrUpdate
      - /iplSuperVisionMain/saveOrUpdate
      - /iplyzgtmain/saveOrUpdate
      - /attachment/getAttachmentByCode
      - /ipldarbmain/exportExcel
      - /iplEsbMain/export/excel
      - /iplManageMain/downloadIplSatbMainDataPkgToExcel/*
      - /iplOdMain/export/excel
      - /iplSuperVisionMain/download
      - /sysCfg/list
      - /sysCfg/pcList

pagehelper:
  auto-dialect: mysql
  params: count=countSql
  support-methods-arguments: true
  reasonable: true